name: Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. v1.2.3, v1.2.3-beta.1)'
        type: string
        required: true
  push:
    branches:
      - master
      - build-jar

jobs:
  Config:
    runs-on: ubuntu-latest
    # version (v1.2.3, v1.2.3-9-adfh), release-name (unstable, stable, v1.2.3)
    outputs:
      version: ${{ steps.version.outputs.version }}
      release-name: "unstable"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Version
        id: version
        run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT
  Build:
    needs: [Config]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #- name: Set current version
      #  id: version
      #  run: echo "git_version=$(git describe --tags)" >> $GITHUB_OUTPUT
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          bb: latest
      - name: Update VERSION
        # run: git describe --tags > VERSION
        run: echo "${{ needs.Config.outputs.version }}" > VERSION
      - name: Build uberjar
        run: bb uberjar deps-try.jar -m eval.deps-try
      - name: Testrun uberjar
        run: bb deps-try.jar -h
      - uses: actions/upload-artifact@v3
        with:
          name: deps-try-latest.jar
          path: deps-try.jar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: >
            version: ${{ needs.Config.outputs.version }}
            SHA: ${{ github.sha }}
          prerelease: true
          name: ${{ needs.Config.outputs.release-name }}
          target_commitish: 55863dbc940e0741b9d9b3a1b11fdbadd08e8bb5 # first commit
          tag_name: ${{ needs.Config.outputs.release-name }}
          files: deps-try.jar
