name: Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. v1.2.3, v1.2.3-beta.1)'
        type: string
        required: true
  push:
    branches:
      - master
      - build-jar

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          bb: latest
      - name: Update VERSION
        run: git describe --tags > VERSION
      - name: Build uberjar
        run: bb uberjar deps-try.jar -m eval.deps-try
      - name: Testrun uberjar
        run: bb deps-try.jar -h
      - uses: actions/upload-artifact@v3
        with:
          name: deps-try-latest.jar
          path: deps-try.jar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: '**This release exists only to have a stable download link**'
          prerelease: true
          name: nightly
          target_commitish: ${{ github.sha }}
          #tag_name: nightly
          files: deps-try.jar
          draft: true
